# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXtsvaEdo44vsMe0BS_d6p3aBcVN21tU
"""

import matplotlib.pyplot as plt
import numpy as np

y = np.array([3,8,1,10])

plt.plot(y, 'o:r')
plt.show()